### ISSUE TITLE
Add Gutenberg blocks for use instead of shortcodes

### ISSUE THREAD

**Issue by polevaultweb** [WPUserManager/wp-user-manager#82]
## Todo
- [x] create blocks for all shortcodes
- [x] when creating pages on installation, detect if classic editor installed and insert the block template instead of shortcode (use_block_editor_for_post_type)
- [ ] ~~block styling~~
- [x] extend group block for the restrict content shortcodes
- [x] Allow the Registration Forms addon to extend the block, add a form_id setting

## Blocks

- [x] Account page
- [x] Login form
- [x] Registration form
- [x] login link
- [x] logout link
- [x] password recovery form
- [x] Profile page
- [x] Profile card
- [x] Directory
- [x] Recently registered
- [x] Content logged in
- [x] Content for users
- [x] Content for roles
